### ISSUE TITLE
What is the VRAM requirements for NeTI?

### ISSUE THREAD

**Issue by ninjasaid2k** [NeuralTextualInversion/NeTI#1]

**Comment by NeuralTextualInversion** [comment]
For training, we require about 17GB of RAM. For inference, this can be done with around 5GB. 
The reason for this is that the current implementation of XTI's attention processor prevents us from using diffuser's `enable_xformers_memory_efficient_attention` processor.
In order to reduce the memory requirements, you can try incorporating the efficient attention to our processor. 
Another way to reduce the requirement is using the 8-bit Adam optimizer using `bitandbytes` like what is done [here](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth). 
I will look into both of these options to see if we can reduce the memory requirements.
