### ISSUE TITLE
Can NeTI do style transfer?

### ISSUE THREAD

**Issue by rivergold** [NeuralTextualInversion/NeTI#3]
In the paper "An Image is Worth One Word: Personalizing Text-to-Image Generation using Textual Inversion" that text inversion can do style transfer. I think that NeTI can also do this. But there are no related experiments in NeTI paper.
So is it possible to make NeTI do style transfer?

**Comment by NeuralTextualInversion** [comment]
Of course. Style transfer will work just like in TI. We have one small example in the paper (you can also find it on our [website](https://neuraltextualinversion.github.io/NeTI/) under "Controlling the Editability with Nested Dropout". We didn't provide a lot of examples in the paper because it was less of a focus in this work.
